sudo: enabled
language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
    - $HOME/.npm
branches:
  only:
    - master
install:
  - npm i
  - npm i ramster
  - npm i mocha -g
scripts:
  - npm run test-travis
